//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoChannel.Test.Services.PingPong
{
    [global::System.CodeDom.Compiler.GeneratedCode("ProtoChannel.CodeGenerator", "1.0.0.0")]
    internal partial class ClientService : global::ProtoChannel.ProtoClient
    {
        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPEndPoint remoteEndPoint)
            : base(remoteEndPoint)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPEndPoint remoteEndPoint, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(remoteEndPoint, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPAddress address, int port)
            : base(address, port)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPAddress address, int port, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(address, port, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(string hostname, int port)
            : base(hostname, port)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(string hostname, int port, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(hostname, port, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Services.PingPong.Pong Ping(global::ProtoChannel.Test.Services.PingPong.Ping message)
        {
            return EndPing(BeginPing(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginPing(global::ProtoChannel.Test.Services.PingPong.Ping message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Services.PingPong.Pong), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Services.PingPong.Pong EndPing(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Services.PingPong.Pong)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public void OneWayPing(global::ProtoChannel.Test.Services.PingPong.OneWayPing message)
        {
            PostMessage(message);
        }
    }
}
