﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoChannel.Test.Service
{
    [global::System.CodeDom.Compiler.GeneratedCode("codegen", "1.0.3.0")]
    internal partial class ClientService : global::ProtoChannel.ProtoClient
    {
        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPEndPoint remoteEndPoint)
            : base(remoteEndPoint)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPEndPoint remoteEndPoint, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(remoteEndPoint, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPAddress address, int port)
            : base(address, port)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(global::System.Net.IPAddress address, int port, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(address, port, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(string hostname, int port)
            : base(hostname, port)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public ClientService(string hostname, int port, global::ProtoChannel.ProtoClientConfiguration configuration)
            : base(hostname, port, configuration)
        {
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.Pong Ping(global::ProtoChannel.Test.Service.Ping message)
        {
            return EndPing(BeginPing(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginPing(global::ProtoChannel.Test.Service.Ping message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.Pong), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.Pong EndPing(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.Pong)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public void OneWayPing(global::ProtoChannel.Test.Service.OneWayPing message)
        {
            PostMessage(message);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public void StreamUpload(global::ProtoChannel.Test.Service.StreamResponse message)
        {
            PostMessage(message);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.StreamResponse StreamRequest(global::ProtoChannel.Test.Service.StreamRequest message)
        {
            return EndStreamRequest(BeginStreamRequest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginStreamRequest(global::ProtoChannel.Test.Service.StreamRequest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.StreamResponse), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.StreamResponse EndStreamRequest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.StreamResponse)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.DefaultValueTests DefaultValueTest(global::ProtoChannel.Test.Service.DefaultValueTests message)
        {
            return EndDefaultValueTest(BeginDefaultValueTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginDefaultValueTest(global::ProtoChannel.Test.Service.DefaultValueTests message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.DefaultValueTests), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.DefaultValueTests EndDefaultValueTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.DefaultValueTests)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.StringArrayTest StringArrayTest(global::ProtoChannel.Test.Service.StringArrayTest message)
        {
            return EndStringArrayTest(BeginStringArrayTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginStringArrayTest(global::ProtoChannel.Test.Service.StringArrayTest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.StringArrayTest), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.StringArrayTest EndStringArrayTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.StringArrayTest)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.IntArrayTest IntArrayTest(global::ProtoChannel.Test.Service.IntArrayTest message)
        {
            return EndIntArrayTest(BeginIntArrayTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginIntArrayTest(global::ProtoChannel.Test.Service.IntArrayTest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.IntArrayTest), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.IntArrayTest EndIntArrayTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.IntArrayTest)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.NestedTypeTest NestedTypeTest(global::ProtoChannel.Test.Service.NestedTypeTest message)
        {
            return EndNestedTypeTest(BeginNestedTypeTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginNestedTypeTest(global::ProtoChannel.Test.Service.NestedTypeTest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.NestedTypeTest), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.NestedTypeTest EndNestedTypeTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.NestedTypeTest)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.NestedTypeArrayTest NestedTypeArrayTest(global::ProtoChannel.Test.Service.NestedTypeArrayTest message)
        {
            return EndNestedTypeArrayTest(BeginNestedTypeArrayTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginNestedTypeArrayTest(global::ProtoChannel.Test.Service.NestedTypeArrayTest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.NestedTypeArrayTest), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.NestedTypeArrayTest EndNestedTypeArrayTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.NestedTypeArrayTest)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.ThrowingTest ThrowingMethod(global::ProtoChannel.Test.Service.ThrowingTest message)
        {
            return EndThrowingMethod(BeginThrowingMethod(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginThrowingMethod(global::ProtoChannel.Test.Service.ThrowingTest message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.ThrowingTest), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.ThrowingTest EndThrowingMethod(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.ThrowingTest)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithEnum EnumTest(global::ProtoChannel.Test.Service.MessageWithEnum message)
        {
            return EndEnumTest(BeginEnumTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginEnumTest(global::ProtoChannel.Test.Service.MessageWithEnum message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.MessageWithEnum), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithEnum EndEnumTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.MessageWithEnum)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithNestedTypes NestedClassTypeTest(global::ProtoChannel.Test.Service.MessageWithNestedTypes message)
        {
            return EndNestedClassTypeTest(BeginNestedClassTypeTest(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginNestedClassTypeTest(global::ProtoChannel.Test.Service.MessageWithNestedTypes message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.MessageWithNestedTypes), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithNestedTypes EndNestedClassTypeTest(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.MessageWithNestedTypes)EndSendMessage(asyncResult);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithCircularReference CircularReference(global::ProtoChannel.Test.Service.MessageWithCircularReference message)
        {
            return EndCircularReference(BeginCircularReference(message, null, null));
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::System.IAsyncResult BeginCircularReference(global::ProtoChannel.Test.Service.MessageWithCircularReference message, global::System.AsyncCallback callback, object asyncState)
        {
            return BeginSendMessage(message, typeof(global::ProtoChannel.Test.Service.MessageWithCircularReference), callback, asyncState);
        }

        [global::System.Diagnostics.DebuggerStepThrough]
        public global::ProtoChannel.Test.Service.MessageWithCircularReference EndCircularReference(global::System.IAsyncResult asyncResult)
        {
            return (global::ProtoChannel.Test.Service.MessageWithCircularReference)EndSendMessage(asyncResult);
        }
    }
}
